### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by ibuilder** [va3c/RvtVa3c#1]
Are there instructions on how to install this plugin and export models?

**Comment by jeremytammik** [comment]
all revit add-ins are installed the same way: place the add-in manifest in a specific folder that revit looks at and loads. the add-in manifest with the filename extension *.addin specifies the location of the .NET assembly DLL. for a simple add-in, i specify no path, just the DLL name, and place it in the same folder. if you simply compile the add-in in Visual Studio, it will copy the add-in manifest and DLL to the right location for you automatically. for more info, look at the revit api getting started material: http://thebuildingcoder.typepad.com/blog/about-the-author.html#2

**Comment by ibuilder** [comment]
Awesome.
