### ISSUE TITLE
Asking HELP for transform matrix assembly

### ISSUE THREAD

**Issue by flower4wine** [va3c/RvtVa3c#10]
Jeremy,

Actually it's not an issue but a question. I'm working on a viewer with customized json format. However, I have some problem while tring to reuse geometry of family symbol with different transform. 

As you mentioned in "the building coder", Revit API only provides a high level Transform class to expose matrix transformation relative information. But I need to assemble transformation MATRIX in a double array.

Here is my code to assemble transformation matrix:

```
Transform t = InstanceNode.GetTransform();
double[] matrix = new double[]
{
    t.BasisX.X * t.Scale, t.BasisX.Y,               t.BasisX.Z,               glOrigin.X, 
    t.BasisY.X,               t.BasisY.Y * t.Scale, t.BasisY.Z,               glOrigin.Y, 
    t.BasisZ.X,               t.BasisZ.Y,               t.BasisZ.Z * t.Scale, glOrigin.Z 
 };
```

And the frustrated render looks as screenshot rst_basic_sample_project (with transformation issue).
![rst_basic_sample_project with transformation issue](https://cloud.githubusercontent.com/assets/8189254/11400007/c33eb68e-93c5-11e5-928c-f5d55d40656c.png)

I checked the transform property of a couple of elements and found that:
1. elements with no rotation (3x3 identity, no matter what origin is) are rendered correctly.
2. elements with rotation are rendered incorrectly (direction is correct, but position is wrong) 

The most possible reason is that I assemle transformation matrix in a wrong way. Could you please help take a look and give me some tips? Thanks a lot!

David

**Comment by flower4wine** [comment]
I found out the root cause: family instance with both GeometryInstance and Solid has already transformed its vertex to world coordinates system, while family instance with only GeometryInstance has vertex in local coordinates system and must we apply transform to put it into world coordinates system. 

I cannot find any clues in Revit API document and even in your blog (the building coder). That's definitely a "pitfall" :-)

Now my question changes to: 
1. Is there any flag of element indicating the difference I mentioned above?
2. STILL: how to assembly transformation for a family instance manually from Revit coordinates system to OpenGL coordinates system?

Thanks in advance!

David

**Comment by jeremytammik** [comment]
Dear David, 

I discussed this with my colleagues. One suggested: 

Answering from top of my head... I think that for _system families_ coordinates always come in WCS while for _standard (RFA) ones_ they are transformed. BUT, the bottom line is that one should ALWAYS use the .Transform (or inverse, not 100% sure) matrix to apply it to the geometry (and accumulate Transforms for nested geometries). It will “come out in the wash” that for system families the transform is identity!

I also think there is something like .GetTransformed(…) method for some concepts that already gets everything in transformed system…

It may be more complicated, though.

Another external developer reported:

Dear support team,

I'm working on exporting a model to my own format. Of course I use the CustomExporter and IExportContext.

I'm almost done with it. The model exports properly and when I read it in an external app, I see almost the same model as in Revit. 'Almost' means that with some objects I have a problem. In the external app, these objects are in a wrong position.

My algorithm is pretty simple. I read the mesh information in the method OnPolymesh. If the object is an instance, i.e. Family Instance, it has a transform. So in the external app a create a mesh and then apply a transformation to it to put it to the correct location, and rotate.
For system objects like Walls, Floors etc I create only the mesh without transformation.

But with some of the family instances there is a problem. in a model they looks the same.
I noticed, that polygons XYZ coordinates are different for different instances. And in fact, if do not apply a transformation to these object, they are on the correct location in an external app.
That means that for some family instances I have not to apply transform (like for a wall).
I started to find the way how to determine such kind of objects.

After comparison a properties, I've found the property Transform.IsTranslation. Excellent, I thought. So if this property is true, I have to apply the transform to mesh. If false, I should not.

But I was wrong. After I considered this property, most of the objects which were in a wrong place became in a correct location, but some of the objects, which were in a correct location, came in a wrong location.

I.e., for some of the objects I have to apply transform and for some of them, I have not.
But how to determine it? I don't have more ideas.

For example, Structural Columns. Some of the instances has Transform.IsTranslation = false, Some of them = true. But in some cases, even if the Transform.IsTranslation = false, I need to apply the translation. Therefore I cannot rely on this property value.

I attached 2 screenshots:

Columns1.png
Columns2.png

The first one shows how the objects look in Revit and the second one how they look in External app after import.

In the second screenshot you can see less columns than in the first one. In actual fact there are the same number of columns, but some of them are in the same place.

Please point me to the correct way and say what I missed.

I am still exploring this issue and would love to summarise the final resolution in a blog post.

So please let me know how you end up resolving this.

Thank you!

Cheers, Jeremy.

**Comment by flower4wine** [comment]
Thanks a lot!

As far as I understand, IExportContext.OnPolymesh() doesn't provide consistent mesh with transform setting. GetTransformed() with Transform.Identity seems to be promising, but that means we still need to parse geometry of element instead of parameter of IExportContext interface method.

Anyway, my method (kind of ugly i know) works now. So I'll leave things that way and keep an eye on what Revit API will expose in the next version :-)

**Comment by jeremytammik** [comment]
Dear David,

glad it helped.

Can you please clarify what your 'kind of ugly' method consist of exactly?

Is it possible to encapsulate it into a pull request, so that it makes it into the main code stream for others to enjoy as well?

Thank you!

Cheers, 

Jeremy

**Comment by flower4wine** [comment]
Jeremy,

That's my pleasure! 
I'm on a business trip preparation today, so I'll get it done by this week.

David

**Comment by flower4wine** [comment]
Jeremy,

My current exportion is multiple json file instead of single json file, code is totally different from RvtVa3c. So I think it's more straightforward to paste code here.

IExportContext.OnPolymesh(PolymeshTopology polymesh)
{
    XYZ vertex = meshPts[vertexIndex];
    if (!(ElementUtils.HasSolid(mCurrRevitElem)))
    {
        Transform t = mTransformStack.Peek();
        vertex = t.OfPoint(vertex);
    }
        // XyzGL is to transform coordination system from Revit to WebGL
    XyzGL glVertex = new XyzGL(vertex);
}

public static bool HasSolid(Autodesk.Revit.DB.Element revitElem)
{
    bool hasSolid = false;

```
Autodesk.Revit.DB.Document revitDoc = revitElem.Document;
Options option = revitDoc.Application.Create.NewGeometryOptions();
option.View = revitElem.Document.ActiveView;
GeometryElement geomElem = revitElem.get_Geometry(option);

foreach (GeometryObject geomObj in geomElem)
{
    if (geomObj is Solid)
    {
        Solid solid = geomObj as Solid;
        if (solid.Volume > 0)
        {
            hasSolid = true;
            break;
        }
    }
}

return hasSolid;
```

}

David
