### ISSUE TITLE
Add Rooms (new feature)

### ISSUE THREAD

**Issue by Tamu** [va3c/RvtVa3c#11]
Hi Jeremy,

I play for a few weeks with the exporter and I would Add an new function : Possibility to export rooms (volumes).
I think this could be a nice feature !
I started by creating data to "_objects" (userData...) but I have problems for adding geometry ( in "_geometries") !

I don't know how I can implement correctly this geometry function  (actually, I don't have created 3D rooms in the 3D view) ?

Thank you for your help.

Cheers
Thomas

**Comment by Tamu** [comment]
For the first step, I create a new function to create 3D Rooms with Revit Family :
[GitHub : Revit3Drooms](https://github.com/Tamu/Revit3Drooms)

I'm still not happy with the performance, but I think we can make a lighter function... thanks for your suggestions !

**Comment by jeremytammik** [comment]
dear thomas, that sounds like a great idea. oh no, creating a conceptual mass for each room is definitely terribly inefficient. it would probably be much easier to use the room ClosedShell property. if you want a real Revit database element to represent the room, you can create a DirectShape element from the closed shell. then you have the 3D shape right there. you can also look at the techniques that people use for the Forge Viewer:

http://thebuildingcoder.typepad.com/blog/2016/06/highlighting-revit-rooms-in-the-forge-viewer.html#3

http://thebuildingcoder.typepad.com/blog/2016/06/highlighting-revit-rooms-in-the-forge-viewer.html#4

**Comment by Tamu** [comment]
Big Thanks Jeremy, I will try with the DirectShape element and push the update ! That sounds much better! 😄

**Comment by Tamu** [comment]
It's done with DirectShape ! Really effective! 👍 
How can I copy Family Parameters (value) in the DirectShape element ? 
Big Thanks.

**Comment by jeremytammik** [comment]
thank you for your appreciation. glad it works and you like it. you can either create a shared parameter or store it in extensible storage. please ask all further questions in public in the revit api discussion forum, and take a look at this thread:

http://forums.autodesk.com/t5/revit-api/write-custom-metadata-to-a-revit-project-via-api/m-p/6501585

**Comment by Tamu** [comment]
just for info .... I make an update with the DirectShape approach :
[GitHub : Revit3Drooms](https://github.com/tamu/Revit3Drooms)

Maybe it can help someone 👍

**Comment by jeremytammik** [comment]
thank you! it would help if you could add a full reproducible case, so that people can test it right out of the box, i.e. solution code, external command to drive it, and sample revit model to run it in. more details here http://thebuildingcoder.typepad.com/blog/about-the-author.html#1b. alternatively, would you like to describe in detail what it does, what input it takes, output, etc. then i can happily publish it on The Building Coder. thank you!

**Comment by Tamu** [comment]
Both ideas are great! I'll work on it!

**Comment by jeremytammik** [comment]
any update on this?

**Comment by Tamu** [comment]
Hi Jeremy,
I still have not managed to finish it. (I have some problems with Sort Curves, Even with SortCurvesContiguous class)  

I try to understand the problem and I come back for news !

**Comment by jeremytammik** [comment]
np... in case of questions, ask away. good luck!

**Comment by jeremytammik** [comment]
how is it going? can i close this issue?

**Comment by bigstone82** [comment]
yes.Thank you for answering my question.------------------------------------------------------------------发件人：Jeremy Tammik <notifications@github.com>发送时间：2017年6月29日(星期四) 21:56收件人：va3c/RvtVa3c <RvtVa3c@noreply.github.com>抄　送：Subscribed <subscribed@noreply.github.com>主　题：Re: [va3c/RvtVa3c] Add Rooms (new feature) (#11) how is it going? can i close this issue?

**Comment by Tamu** [comment]
Hi Jeremy, yes for me you can close this issue. Big thanks
