### ISSUE TITLE
why there's a 0 value index added for each triangle?

### ISSUE THREAD

**Issue by flower4wine** [va3c/RvtVa3c#12]
Hi Jeremy,

While reading the export logic in OnPolymesh(), I notice that you insert a 0 value index for every triangle.

int v1, v2, v3;
foreach (PolymeshFacet facet in polymesh.GetFacets())
{
	//Debug.WriteLine( string.Format("      {0}: {1} {2} {3}", i++, facet.V1, facet.V2, facet.V3 ) );

	v1 = CurrentVerticesPerMaterial.AddVertex(new PointInt(pts[facet.V1], _switch_coordinates));
	v2 = CurrentVerticesPerMaterial.AddVertex(new PointInt(pts[facet.V2], _switch_coordinates));
	v3 = CurrentVerticesPerMaterial.AddVertex(new PointInt(pts[facet.V3], _switch_coordinates));

	**CurrentGeometryPerMaterial.data.faces.Add(0);**
	CurrentGeometryPerMaterial.data.faces.Add(v1);
	CurrentGeometryPerMaterial.data.faces.Add(v2);
	CurrentGeometryPerMaterial.data.faces.Add(v3);
}

I'm quite confused by this line. IMHO, this 0 value index will make mesh messed up. However, va3c viewer renders model fine. Could you please give me a hint of it? Thanks a lot!

Cheers!
David Tan

**Comment by jeremytammik** [comment]
look at the comment on the definition of `Va3cGeometryData.faces`. it says: indices into Vertices + Materials. the zero is probably the material index, the following three the three triangular face vertex indices.

**Comment by flower4wine** [comment]
thanks a lot!
