### ISSUE TITLE
Failing to integrate add-in after building RvtVa3c (VS 2015, Dynamo 1.3, Revit 2017)

### ISSUE THREAD

**Issue by HaloAR** [va3c/RvtVa3c#13]
I downloaded latest release 2017.0.0.0 and built in VS 2017 using DLLs from Dynamo 1.3 and Revit 2017 which were:
RevitNodes.resources.dll; DynamoCore.dll; RevitRaaS.dll; DynamoServices.dll; DSCoreNodes.dll; DynamoRevitDS.dll; DynamoCore.resources.dll; DynamoUtilities.dll; ProtoCore.dll; RevitServices.dll; RevitNodes.dll; DynamoRaaS.dll; DSRevitNodesUI.customization.dll; DSRevitNodesUI.dll; RevitAPIUI.dll; RevitAPI.dll

I generated the DLL into Autodesk/Revit 2017/AddIns/rvt/, and also copied NewtonSoft.json.dll and RvtVa3c.addin

The add in doesn't show in either the add in tab or as an export option when testing with a basic wall or with the sample projects.

**Comment by jeremytammik** [comment]
i do not use the dynamo parts of this and have no idea what might be going wrong there. all i know is the pure revit add-in, which compiles just find referencing only RevitAPIUI.dll and RevitAPI.dll. i just migrated to Revit 2018 to check. i attached a screen snapshot of RvtVa3c loaded in the external tools menu: 
![rvtva3c_2018](https://user-images.githubusercontent.com/4264589/27690936-ea303af0-5ce2-11e7-9957-3219a0e55839.png)
RvtVa3c_2018.png
