### ISSUE TITLE
hello,and an error occurs

### ISSUE THREAD

**Issue by sunhao474** [va3c/RvtVa3c#14]
when i build it, visual studio told me that err: “RvtVa3c.Va3cExportContext”did not 
 implete the member“Autodesk.Revit.DB.IExportContext.OnDaylightPortal(Autodesk.Revit.DB.DaylightPortalNode)”
i do not know what to do next.i use vs 2012 & revit 2015.

**Comment by sunhao474** [comment]
sorry to bother you, but i just find out that this function is removed from revit2017， and i find the function which had been commented

**Comment by jeremytammik** [comment]
congratulations on resolving the issue.
