### ISSUE TITLE
Element without category causes crash

### ISSUE THREAD

**Issue by flower4wine** [va3c/RvtVa3c#4]
Jeremy,

I use RvtVa3c to export a Revit file and encounter crash while doing CustomExporter.Export(). The reason there're some elements with null category property. I think it would be a common situation as I encounter elements with null categroy property in some other Revit files.

My approash is to add the following process in both OnElementBegin() and OnElementEnd(). I'm not sure if it's the right way, but at least it works for me.

```
        if (null == e.Category)
        {
            Debug.WriteLine("\r\n*** Non-category element!\r\n");
            return;
        }
```

David

**Comment by jeremytammik** [comment]
dear david, 

thank you for letting us know!

could you please provide some examples of what these element may be?

if they really can be skipped, i would simply add the following to OnElementBegin:

```
  if( null == e.Category )
  {
    Debug.WriteLine( "\r\n*** Non-category element!\r\n" );
    return RenderNodeAction.Skip;
  }
```

i think that alone should be sufficient, shouldn't it?

cheers

jeremy

**Comment by flower4wine** [comment]
Jeremy,

> > could you please provide some examples of what these element may be?

The elements with null category is type of ImportInstance. The Revit model I'm using is merge result of 2 separated models, one of which is linked into the other.

> > i would simply add the following to OnElementBegin

Per my test, even if I mark RenderNodeAction.Skip as result of OnElementBegin(), the same element will still be processed by OnElementEnd(). So in my case, I have to add skip statements in both of them. I'm using Revit 2015 (EN).

David

**Comment by jeremytammik** [comment]
hi david,

ok, thank you for testing that. 

oh yes, there is even a comment in the OnElementEnd method explicitly pointing that out: "Note: this method is invoked even for elements that were skipped."

i updated the repository code with that as well now. can you please verify that the fixed code in the repository works for you now? thank you!

cheers,

jeremy

**Comment by flower4wine** [comment]
Jeremy,

Sorry! I missed your testing invitation in the last quick glance.
The latest version works fine with my Revit model now :+1: 

David

**Comment by jeremytammik** [comment]
Yay! Thank you for checking and confirming! Cheer, Jeremy.
