### ISSUE TITLE
There's no color configured via filter exported

### ISSUE THREAD

**Issue by flower4wine** [va3c/RvtVa3c#8]
Jeremy,

I exported a small MEP model and found that RvtVa3c skips element colors configured via filter. I tried to find related Revit API which could query element's filter color but there's no luck.

Could you please give me some clues about how to get an element's filter color? Thanks a lot!

David

**Comment by jeremytammik** [comment]
Dear David, does RvtVa3c export its data from the current view? Is the filter set up for that same view? I would assume the the custom exporter does in fact honour all settings, including element filter colours. Can you verify whether the filter really is active for the view that is being used by the RvtVa3c custom exporter? Cheers, Jeremy.

**Comment by jeremytammik** [comment]
hey @flower4wine shall we continue discussing this? otherwise i will close it off. cheers, jeremy

**Comment by flower4wine** [comment]
Jeremy,

Sorry for late response! You know github is blocked in China and on the same time I have been crazy about an issue these days.

I confirmed the settings you mentioned and unfortunately there's still no filter color exported. Now I use predefined color table. Revit filter color could be set per table manually, and exporter should also be coded per table. That resolves my problem, although it's kind of awkward.

David
