### ISSUE TITLE
not able to build

### ISSUE THREAD

**Issue by Fatman13** [va3c/RvtVa3c#9]
Hello, guys,

I am not able to build the solution using vs2015. I am not sure what DScore is. Is it possible that someone could release the built dll? Many thanks in advance. 

![revit](https://cloud.githubusercontent.com/assets/1591330/10685885/7cdf9c1a-7991-11e5-81de-c411363d995f.jpg)

**Comment by jeremytammik** [comment]
hey @Fatman13! the master branch is currently for Revit 2016. it looks as if you are trying to build for an earlier version of Revit. in that case, you have to grab a suitable previous release from the list: https://github.com/va3c/RvtVa3c/releases

**Comment by Fatman13** [comment]
Thanks for the fast reply. I am using revit 2014. I will try an earlier version then.

**Comment by Fatman13** [comment]
hi @jeremytammik , I was able to build 2005.0.0.20 and got following dlls.
![revit10](https://cloud.githubusercontent.com/assets/1591330/10693828/551df1b8-79cd-11e5-82af-dc2310a720cb.jpg)
Then I copy pasted everything to `C:\Program Files\Autodesk\Revit 2014\AddIns\jsonExporter` along with the dot addin file. 
![revit11](https://cloud.githubusercontent.com/assets/1591330/10693846/6a7dd2ee-79cd-11e5-8bcc-7776ca607874.jpg)
But the addin tab never showed up. Even for addins already came with Revit installation. Am I just missing something obvious here?

**Comment by jeremytammik** [comment]
dear @Fatman13 maybe you should read the Revit API getting started material first of all, to understand the basics of installing a Revit add-in: http://thebuildingcoder.typepad.com/blog/about-the-author.html#2

as far as i can tell offhand, the problem may be the `jsonExporter` subdirectory. Revit needs to read the add-in manifest file with the extension `addin`. maybe it only does so when it is in the `AddIns` folder.

**Comment by Fatman13** [comment]
Thanks for pointing to the right material. I think I got it now.
